import { defineConfig } from "oxlint";

export default defineConfig({
  options: { typeAware: true },
  plugins: ["typescript", "import"],
  jsPlugins: [{ name: "anti-slop", specifier: "./vendor/anti-slop/index.ts" }],
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
  },
  rules: {
    "no-unused-vars": "error",
    "no-console": "error",
    eqeqeq: "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-floating-promises": ["error", { ignoreVoid: true }],
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unnecessary-template-expression": "off",
    "typescript/no-base-to-string": "off",
    "typescript/unbound-method": "off",
    "no-await-in-loop": "off",
    "require-yield": "off",

    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
  settings: {},
  env: {
    builtin: true,
    node: true,
  },
  globals: {},
  ignorePatterns: ["vendor/anti-slop/**"],
});
